# Ensures API Gateway can be reached
name: Checking REST Endpoints

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *' 
    
env:
  API_HOST: https://evetrade.space/api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checking Hauling Endpoint
        run: |
          curl -X GET "$API_HOST/hauling?from=10000002&to=10000043&tax=0.08&minProfit=500000&minROI=0.04&maxBudget=99999999999&maxWeight=9999999&routeSafety=secure&systemSecurity=high_sec"

      - name: Checking Resource Endpoint
        run: |
          curl -X GET "$API_HOST/resource?file=invTypes.json"

      - name: Checking Orders Endpoint
        run: |
          curl -X GET "$API_HOST/orders?itemId=33697&from=10000002:60003760&to=10000043:60008494"

      - name: Checking Station Trading Endpoint
        run: |
          curl -X GET "$API_HOST/station?station=60003760&tax=0.08&fee=0.03&margins=0.20,0.40&min_volume=10000&volume_filter=1"
